# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-20 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_sellitem_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellitem',
            name='max_buy',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sellitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10),
            preserve_default=False,
        ),
    ]
