# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-21 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20180320_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellitem',
            name='rating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sellitem',
            name='reviews',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
